
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - master

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: yarn

      - name: 启用 Corepack
        run: corepack enable

      - name: 安装 Yarn 版本
        run: corepack prepare yarn@4.10.3 --activate

      - name: 安装依赖
        run: yarn install --immutable

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: yarn docs:build

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: page # 部署目标分支
          folder: docs/.vuepress/dist # 构建输出目录